# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 19:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='announce_message',
            unique_together=set([('id', 'sniff_timestamp')]),
        ),
        migrations.AlterUniqueTogether(
            name='path_delay_request_message',
            unique_together=set([('id', 'sniff_timestamp')]),
        ),
    ]
